name: Deploy to Tencent COS

on:
  push:
    branches:
      - main   # 当 main 分支更新时触发
  workflow_dispatch: # 可手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 如果是前端项目（例如 React/Vue），需要先构建
      - name: Build static site
        run: |
          npm install
          npm run build
        # 如果你的项目不需要构建（纯静态HTML），可以删除这个步骤

      - name: Install coscmd
        run: pip install coscmd

      - name: Configure coscmd
        run: |
          coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} \
                        -s ${{ secrets.TENCENT_SECRET_KEY }} \
                        -b knowledge-bas-1302891994 \
                        -r ap-beijing

      - name: Upload to COS
        run: |
          coscmd upload -r ./vitepress-docs/.vitepress/dist/ /   # 如果你的构建产物在 dist 目录
          # 或者 coscmd upload -r ./ /  上传整个项目目录
